# 1. Create a 3x3x3 array with random values 

In [2]:
#creating a random array of order 3X3X3
import numpy as np
a=np.empty((3,3,3))
print("The Array is:- ")
print(a)
print("The Shape of Array is:- ")
print(a.shape)

The Array is:- 
[[[  1.29322153e-311   1.29318086e-311   1.69121096e-306]
  [  7.56605919e-307   1.89146896e-307   1.37961302e-306]
  [  1.05699242e-307   8.01097889e-307   1.78020169e-306]]

 [[  7.56601165e-307   1.02359984e-306   1.33510679e-306]
  [  2.22522597e-306   1.24611674e-306   1.29061821e-306]
  [  6.23057349e-307   2.22522597e-306   1.06810268e-306]]

 [[  6.23052935e-307   1.29062025e-306   6.89807188e-307]
  [  1.42418172e-306   1.37961641e-306   1.22383391e-307]
  [  8.45610231e-307   2.46151512e-312   1.29319703e-311]]]
The Shape of Array is:- 
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b=np.zeros((5,5))
print("Initial matrix:- ")
print(b)
for i in range(len(b)):
    for j in range(len(b)):
        if(i==j+1):
            b[i][j]=i
print("Final matrix-")
print(b)

Initial matrix:- 
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Final matrix-
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
c=np.zeros((8,8)) 
print("Initial Matrix-")
print(c)
for i in range(len(c)):
    for j in range(len(c)):
        if(j%2!=0):
            c[i][j]=255
print("Final Matrix-")
print(c)

Initial Matrix-
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
Final Matrix-
[[   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]
 [   0.  255.    0.  255.    0.  255.    0.  255.]]


# 4. Normalize a 5x5 random matrix

In [5]:

d=np.random.randn(5,5)
print("The random matrix is-")
print(d)
normal=np.linalg.norm(d)
print("The norm value of random matrix is-")
print(normal)
e=np.divide(d,normal)
print("The normalized random mattrix is-")
print(e)

The random matrix is-
[[-1.36457019 -1.03285915  1.23054242  0.96380953 -0.31386854]
 [ 1.19060103  1.5354178   0.4369088   0.40753242  0.86841132]
 [-0.48831976 -0.14028895 -0.12270685  0.11743252 -0.26405524]
 [ 0.47845783 -1.0819181  -0.72866937 -0.73871463  0.83036738]
 [ 0.66207721  1.40673535 -0.71442935  1.07105435 -0.0998645 ]]
The norm value of random matrix is-
4.23837380281
The normalized random mattrix is-
[[-0.32195608 -0.24369232  0.29033362  0.22740079 -0.074054  ]
 [ 0.28090987  0.36226578  0.10308407  0.09615302  0.20489257]
 [-0.11521394 -0.03309971 -0.0289514   0.02770698 -0.06230107]
 [ 0.11288712 -0.25526727 -0.17192192 -0.174292    0.1959165 ]
 [ 0.1562102   0.3319045  -0.16856214  0.25270408 -0.02356199]]


# 5.  How to find common values between two arrays?

In [6]:

f=np.array([1,2,3,4,5])
print("The 1st array is-")
print(f)
g=np.array([2,4,6,8,10])
print("The 2nd array is-")
print(g)
com_values=np.intersect1d(f,g)
print("Common values between two arrays are-")
print(com_values)

The 1st array is-
[1 2 3 4 5]
The 2nd array is-
[ 2  4  6  8 10]
Common values between two arrays are-
[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday =np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today= np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-25
Today's Date:  2020-07-26
Tomorrow's Date:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [10]:
x = np.random.randint(0,2,4)
print("First array:")
print(x)
y = np.random.randint(0,2,4)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 1]
Second array:
[1 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[ 0.37531281  0.96725992  0.99886742  0.61679049  0.9700367   0.57838305
  0.5150863   0.69964286  0.15732418  0.42483445]
Maximum value replaced by 0:
[ 0.37531281  0.96725992  0.          0.61679049  0.9700367   0.57838305
  0.5150863   0.69964286  0.15732418  0.42483445]


# 9. How to print all the values of an array?

In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(a)):
    print(a[i])

1
2
3
4
5
6
7
8
9
10


# 10.Subtract the mean of each row of a matrix

In [16]:
arr=np.random.randn(3,3)
print("The matrix is-")
print(arr)
arr2=arr-arr1
print("The matrix after the mean is subtracted-")
print(arr2)

The matrix is-
[[ 1.0931384   1.45917015  0.41140091]
 [ 1.1789485  -0.49349761 -1.42308115]
 [ 1.02520829  0.1225564   0.9932024 ]]
The matrix after the mean is subtracted-
[[ 0.71901698  1.70443759  0.43551589]
 [ 0.80482708 -0.24823017 -1.39896617]
 [ 0.65108688  0.36782384  1.01731738]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [4]:
Z = np.random.randn(10,1)
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)
print("The Index values obtained are:")
print(I)
J=np.unique(I,axis=0)
print("The final unique index values are:")
print(J)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,J,1)
print(Z)

The original vector is:
[[ 0.26923079]
 [ 3.01257086]
 [ 0.67404262]
 [-0.22351919]
 [ 2.14695945]
 [-0.80099751]
 [-0.4739089 ]
 [ 2.2033309 ]
 [-0.2435668 ]
 [ 0.40562673]]
The Index values obtained are:
[8 6 1 9]
The final unique index values are:
[1 6 8 9]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 0.26923079]
 [ 4.01257086]
 [ 0.67404262]
 [-0.22351919]
 [ 2.14695945]
 [-0.80099751]
 [ 0.5260911 ]
 [ 2.2033309 ]
 [ 0.7564332 ]
 [ 1.40562673]]


# 12.How to get the diagonal of a dot product?

In [6]:
u=np.random.randn(3,3)
print("The first 3X3 array is- ")
print(u)
v=np.random.randn(3,3)
print("The second 3X3 array is- ")
print(v)
w=np.dot(u,v)
print("The corresponding dot product is- ")
print(w)
z=np.diag(w)
print("The corresponding diagnol elements are- ")
print(z)

The first 3X3 array is- 
[[ 0.98877471  1.07416036 -0.81840731]
 [-1.30651032  1.49289554 -1.09600241]
 [-1.9858579  -0.51793635  0.62492783]]
The second 3X3 array is- 
[[ 1.21852412  0.46471014  0.14759425]
 [ 0.43668846  1.30428239  0.29511265]
 [-0.4620582   0.28733278  0.85084519]]
The corresponding dot product is- 
[[ 2.05207108  1.62534683 -0.23340215]
 [-0.43366719  1.02509135 -0.68478942]
 [-2.93474561 -1.41882131  0.08576606]]
The corresponding diagnol elements are- 
[ 2.05207108  1.02509135  0.08576606]


# 13.How to find the most frequent value in an array?

In [20]:
x = np.array([1,2,3,4,5,6,7,53,5,7,8,8,7,65,4,3,6,54,52])
print("Original array:")
print(x)
print("Most frequent value in the x array:")
print(np.bincount(x).argmax())

Original array:
[ 1  2  3  4  5  6  7 53  5  7  8  8  7 65  4  3  6 54 52]
Most frequent value in the x array:
7


# 14.How to get the n largest values of an array

In [23]:
M=np.arange(100)
np.random.shuffle(M)
n=int(input("Enter the value of n:"))
print("The",n,"largest value of the array are:")
print (M[np.argpartition(-M,n)[:n]])

Enter the value of n:32
The 32 largest value of the array are:
[83 80 75 85 82 78 92 99 76 86 89 90 88 97 94 79 98 84 91 96 95 77 93 74 73
 87 71 81 72 70 69 68]


# 15.How to create a record array from a regular array?

In [11]:
reg_arr = np.array([["John", 32, 43],["Undertaker", 45, 32],["Randy", 77, 78]])#generates a 2D array
print("Original array:")
print(reg_arr)
print("\nRecord array:")
rec_arr = np.core.records.fromarrays(reg_arr.T,names='col1, col2, col3',formats = 'S80, f8, i8')# generates a reccord array
print(rec_arr)
type(rec_arr)

Original array:
[['John' '32' '43']
 ['Undertaker' '45' '32']
 ['Randy' '77' '78']]

Record array:
[(b'John',  32., 43) (b'Undertaker',  45., 32) (b'Randy',  77., 78)]


numpy.recarray